#! /bin/sh
# /etc/init.d/WeatherBlink

# The following part always gets executed.
echo "This part always gets executed"

# The following part carries out specific functions depending on arguments.
case "$1" in
  start)
    cd /home/pi/code/WeatherBlink/
    python BlinkWeather.py
    ;;
  stop)
    echo "Nothing really happens here"
    ;;
  *)
    echo "Usage: /etc/init.d/foobar {start|stop}"
    exit 1
    ;;
esac

exit 0
